import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "GameHub",
  description: "Generated by create next app",
};

const mockUser = {
  name: "John Doe",  
  avatarUrl: "path-to-avatar.jpg",  
};

const statut = true; 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Injection de mockUser seulement si l'utilisateur est authentifié */}
        <Header isAuthenticated={statut} user={statut ? mockUser : undefined} />
        {children}
      </body>
    </html>
  );
}
